---
# Xiaomi Evaporative Humidifier

- platform: template
  sensors:
    evaporative_humidifier_office_temp:
      value_template: "{{ state_attr('fan.evaporative_humidifier_office', 'temperature') }}"
      unit_of_measurement: "°C"
      device_class: "temperature"
    evaporative_humidifier_office_humidity:
      value_template: "{{ state_attr('fan.evaporative_humidifier_office', 'humidity') }}"
      unit_of_measurement: "%"
      device_class: "humidity"
    evaporative_humidifier_office_speed:
      value_template: "{{ state_attr('fan.evaporative_humidifier_office', 'motor_speed') }}"
      unit_of_measurement: "rpm"
      icon_template: "mdi:speedometer"
    evaporative_humidifier_office_depth:
      value_template: "{{ state_attr('fan.evaporative_humidifier_office', 'depth') }}"
      unit_of_measurement: "%"
      icon_template: "mdi:water"
