---
# Xiaomi Air Purifier 3

- platform: template
  sensors:
    air_purifier_bedroom_temp:
      value_template: "{{ state_attr('fan.air_purifier_bedroom', 'temperature') }}"
      unit_of_measurement: "°C"
      device_class: "temperature"
    air_purifier_bedroom_humidity:
      value_template: "{{ state_attr('fan.air_purifier_bedroom', 'humidity') }}"
      unit_of_measurement: "%"
      device_class: "humidity"
    air_purifier_bedroom_air_quality_pm25:
      value_template: "{{ state_attr('fan.air_purifier_bedroom', 'aqi') }}"
      unit_of_measurement: "μg/m³"
      icon_template: "mdi:weather-fog"
    air_purifier_bedroom_speed:
      value_template: "{{ state_attr('fan.air_purifier_bedroom', 'motor_speed') }}"
      unit_of_measurement: "rpm"
      icon_template: "mdi:speedometer"
    air_purifier_bedroom_filter_remaining:
      value_template: "{{ state_attr('fan.air_purifier_bedroom', 'filter_life_remaining') }}"
      unit_of_measurement: "%"
      icon_template: "mdi:heart-outline"