- alias: Kitchen Pendant Keypad Button Turned On
  trigger:
    platform: state
    entity_id: switch.door_entrance_contact
    to: 'on'
  action:
  - service: python_script.set_state
    data:
      entity_id: binary_sensor.door_entrance_contact
      state: 'on'

- alias: Kitchen Pendant Keypad Button Turned Off
  trigger:
    platform: state
    entity_id: switch.door_entrance_contact
    to: 'off'
  action:
  - service: python_script.set_state
    data:
      entity_id: binary_sensor.door_entrance_contact
      state: 'off'