homeassistant:
  external_url: "https://sweethomeha.duckdns.org"

  # Load packages
  packages: !include_dir_named integrations
  media_dirs:
    local: /media

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - ::1
    - 172.30.32.0/24 

logger:
  default: warning
  logs:
    custom_components.xiaomi_miot: debug

python_script:

# xiaomi_miot:
#   username: !secret xiaomi-cloud-username
#   password: !secret xiaomi-cloud-password
#   server_country: cn
#   device_customizes:
#     mmgg.feeder.fi1:
#       chunk_properties: 1
#       exclude_miot_services: ''
#       exclude_miot_properties: contrycode,factory_result

#     fan.zhimi_ma4_708e_air_purifier:
#       interval_seconds: 30
#       chunk_properties: 10
#       miot_local: true

default_config:
