title: Dom
views:
  - title: Home
    icon: mdi:home
    badges:
        - entity: binary_sensor.rpi_power_status
        - entity: sensor.cpu_temp
        - entity: sensor.gpu_temp
        - entity: sensor.cpu_clock
        - entity: person.wojciech
        - entity: person.justyna
        - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.dom
      - title: People at home
        type: entities
        entities:
          - switch.door_entrance_contact
          - input_boolean.justyna_home
          - input_boolean.justyna_wifi
          - input_boolean.wojciech_home
          - input_boolean.wojciech_wifi

      - type: vertical-stack
        cards:
          - title: Okna
            type: glance
            columns: 3
            entities:
              - binary_sensor.window_kitchen_contact
              - binary_sensor.window_office_contact
              - binary_sensor.window_bedroom_contact
          - title: Drzwi
            type: glance
            columns: 3
            entities:
              - binary_sensor.door_entrance_contact
              - binary_sensor.door_bedroom_contact
              - binary_sensor.door_bathroom_contact

      - title: Środowisko
        type: entities
        entities:
          - entity: sensor.ht_temperature_balcony
            type: custom:multiple-entity-row
            name: Balkon
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_balcony
          - entity: sensor.ht_temperature_living_room
            type: custom:multiple-entity-row
            name: Salon
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_living_room
          - entity: sensor.ht_temperature_office
            type: custom:multiple-entity-row
            name: Biuro
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_office
          - entity: sensor.evaporative_humidifier_office_temp
            type: custom:multiple-entity-row
            name: Korytarz
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.evaporative_humidifier_office_humidity
          - entity: sensor.ht_temperature_bathroom
            type: custom:multiple-entity-row
            name: Łazienka
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_bathroom
          - entity: sensor.air_purifier_bedroom_temp
            type: custom:multiple-entity-row
            name: Sypialnia
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Powietrze
                entity: sensor.air_purifier_bedroom_air_quality_pm25
              - name: Wilgotność
                entity: sensor.air_purifier_bedroom_humidity

  - title: Kuchnia
    icon: mdi:silverware-fork-knife
    cards:
      - title: Światło
        show_header_toggle: false
        type: entities
        entities:
          - type: custom:multiple-entity-row
            entity: light.light_2_kitchen
            name: Aneks kuchenny
            state_header: Sufit 2
            toggle: true
            state_color: true
            entities:
              - name: Blat
                entity: light.shelly_kitchen_desk
                toggle: true
              - name: Sufit 1
                entity: light.light_1_kitchen
                toggle: true
          - light.shelly_kitchen_table
          - type: custom:multiple-entity-row
            entity: switch.fan_2_kitchen
            name: Wiatrak kuchenny
            state_header: Bieg 2
            toggle: true
            entities:
              - name: Bieg 1
                entity: switch.fan_1_kitchen
                toggle: true


  - title: Salon
    icon: mdi:sofa
    cards:
      - title: Światło
        type: entities
        entities:
          - light.gateway_light_living_room
          - light.coffee_table_light_living_room
      - title: Rozrywka
        type: entities
        entities:
          - type: "custom:mini-media-player"
            entity: media_player.android_tv
            name: Android TV
            info: short
      - title: Nawilżacz powietrza
        type: entities
        entities:
          - fan.evaporative_humidifier_office
          - switch.evaporative_humidifier_office_automations_enabled
          - input_select.evaporative_humidifier_office_mode
          - input_number.evaporative_humidifier_office_led_brightness
          - switch.evaporative_humidifier_office_dry
          - switch.evaporative_humidifier_office_child_lock
          - switch.evaporative_humidifier_office_buzzer
          - sensor.evaporative_humidifier_office_speed
          - sensor.evaporative_humidifier_office_depth
        show_header_toggle: false
        theme: default
      - title: Odkurzacz
        type: "custom:vacuum-card"
        entity: vacuum.vacuum_roborock_s50
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
          cleaning:
            - attribute: cleaned_area
              unit: m2
              subtitle: Cleaning area
            - attribute: cleaning_time
              unit: minutes
              subtitle: Cleaning time
        actions:
          - name: Clean entrance
            service: script.clean_entrance
            icon: "mdi:door"
          - name: Clean hall
            service: script.clean_hall
            icon: "mdi:walk"
          - name: Clean kitchen
            service: script.clean_kitchen
            icon: "mdi:silverware-fork-knife"
          - name: Clean living room
            service: script.clean_living_room
            icon: "mdi:sofa"
          - name: Clean office
            service: script.clean_office
            icon: "mdi:laptop-windows"
          - name: Clean bathroom
            service: script.clean_bathroom
            icon: "mdi:shower"
          - name: Clean bedroom
            service: script.clean_bedroom
            icon: "mdi:bed-empty"
          - name: Clean entire home
            service: script.clean_entire_home
            icon: "mdi:home"

  - title: Biuro
    icon: mdi:laptop-windows
    cards:
      - title: Światło
        type: entities
        entities:
          - light.mi_led_desk_lamp

  - title: Korytarz
    icon: mdi:walk
    cards:
      - title: Światło
        type: entities
        entities:
          - light.gateway_light_hall
          - light.light_1_hall
  
  - title: Sypialnia
    icon: mdi:bed-empty
    cards:
      - title: Światło
        type: entities
        entities:
          - light.yeelight_color_bedroom
      - title: Oczyszczacz powietrza
        type: entities
        entities:
          - fan.air_purifier_bedroom
          - switch.air_purifier_bedroom_automations_enabled
          - input_select.air_purifier_bedroom_mode
          - input_number.air_purifier_bedroom_favorite_level
          - input_number.air_purifier_bedroom_fan_level
          - switch.air_purifier_bedroom_child_lock
          - switch.air_purifier_bedroom_led
          - switch.air_purifier_bedroom_buzzer
          - sensor.air_purifier_bedroom_speed
          - sensor.air_purifier_bedroom_filter_remaining
        show_header_toggle: false
        theme: default