title: Dom
views:
  - title: Home
    icon: mdi:home
    badges:
        - entity: binary_sensor.rpi_power_status
        - entity: sensor.cpu_temp
        - entity: sensor.gpu_temp
        - entity: sensor.cpu_clock
        - entity: person.wojciech
        - entity: person.justyna
        - entity: device_tracker.person_luna
        - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.dom
      - type: vertical-stack
        cards:
          - title: Rodzina
            type: entities
            show_header_toggle: false
            entities:
              - entity: person.justyna
                type: custom:multiple-entity-row
                show_state: false
                secondary_info:
                  entity: person.justyna
                  name: false
                entities: 
                  - name: WiFi
                    entity: binary_sensor.justyna_wifi
                    state_color: true
                  - name: Poziom baterii
                    entity: sensor.oneplus_7t_poziom_baterii              
                  # - name: W domu
                  #   entity: input_boolean.justyna_home
              - entity: person.wojciech
                type: custom:multiple-entity-row
                show_state: false
                secondary_info:
                  entity: person.wojciech
                  name: false
                entities:
                  - name: WiFi
                    entity: binary_sensor.wojciech_wifi
                    state_color: true
                  - name: Poziom baterii
                    entity: sensor.oneplus_7_battery_level
                  # - name: W domu
                  #   entity: input_boolean.wojciech_home
              - entity: device_tracker.person_luna
                type: custom:multiple-entity-row
                show_state: false
                secondary_info:
                  entity: device_tracker.person_luna
                  name: false
                entities:
                  - name: Ruch w kuwecie
                    entity: binary_sensor.binary_sensor_motion_sensor_door_entrance_occupancy
              # - switch.wardrobe_entrance_contact
              # - input_boolean.wojciech_wifi
              # - input_boolean.justyna_wifi
              # - input_boolean.wojciech_home
              # - input_boolean.justyna_home
          - type: entity-filter
            show_empty: false
            card:
              title: Światło
              show_header_toggle: false
            entities:
              - switch.light_1_entrance
              - switch.light_1_ceiling_kitchen
              - switch.light_2_ceiling_kitchen
              - switch.light_desk_kitchen
              - switch.light_table_kitchen
              - switch.light_1_hall
              - switch.light_coffee_table_living_room
              - light.mi_led_desk_lamp
              - light.yeelight_color_bedroom
              - light.gateway_light_hall
              - light.gateway_light_living_room
              - switch.fan_1_kitchen
              - switch.fan_2_kitchen
              - switch.light_1_office
            state_filter: 
              - 'on'
          - type: entity-filter
            show_empty: false
            card:
              title: Rozrywka
              show_header_toggle: false
            entities:
              - type: "custom:mini-media-player"
                entity: media_player.sony_kdl_50w809c
                hide:
                  source: true
              - type: "custom:mini-media-player"
                entity: media_player.projector_bedroom
                hide:
                  source: true
            state_filter:
              - 'on'
              - 'idle'
              - 'paused'
              - 'playing'
      - type: vertical-stack
        cards:
          - title: Okna
            type: glance
            columns: 3
            entities:
              - binary_sensor.window_kitchen_contact
              - binary_sensor.window_office_contact
              - binary_sensor.window_bedroom_contact
          - title: Drzwi
            type: glance
            columns: 4
            entities:
              - binary_sensor.door_entrance_contact
              - binary_sensor.door_bedroom_contact
              - binary_sensor.door_bathroom_contact
              - binary_sensor.door_cat_toilet_contact
              - binary_sensor.wardrobe_entrance_contact
      - title: Środowisko
        type: entities
        entities:
          - entity: sensor.ht_temperature_balcony
            type: custom:multiple-entity-row
            name: Balkon
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_balcony
          - entity: sensor.ht_temperature_living_room
            type: custom:multiple-entity-row
            name: Salon
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_living_room
          - entity: sensor.ht_temperature_office
            type: custom:multiple-entity-row
            name: Biuro
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_office
          - entity: sensor.evaporative_humidifier_office_temperature
            type: custom:multiple-entity-row
            name: Korytarz
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.evaporative_humidifier_office_humidity
          - entity: sensor.ht_temperature_bathroom
            type: custom:multiple-entity-row
            name: Łazienka
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Wilgotność
                entity: sensor.ht_humidity_bathroom
          - entity: sensor.air_purifier_bedroom_temperature
            type: custom:multiple-entity-row
            name: Sypialnia
            state_header: Temperatura
            secondary_info: last-changed
            entities:
              - name: Powietrze
                entity: sensor.air_purifier_bedroom_pm2_5
              - name: Wilgotność
                entity: sensor.air_purifier_bedroom_humidity

  - title: Wejście
    icon: mdi:door
    cards:
      - title: Światło
        type: entities
        entities:
          - switch.light_1_entrance

  - title: Kuchnia
    icon: mdi:silverware-fork-knife
    cards:
      - title: Światło
        show_header_toggle: false
        type: entities
        entities:
          - type: custom:multiple-entity-row
            entity: switch.light_2_ceiling_kitchen
            name: Aneks kuchenny
            state_header: Sufit 2
            toggle: true
            state_color: true
            entities:
              - name: Blat
                entity: switch.light_desk_kitchen
                toggle: true
              - name: Sufit 1
                entity: switch.light_1_ceiling_kitchen
                toggle: true
          - switch.light_table_kitchen
          - type: custom:multiple-entity-row
            entity: switch.fan_2_kitchen
            name: Wiatrak kuchenny
            state_header: Bieg 2
            toggle: true
            entities:
              - name: Bieg 1
                entity: switch.fan_1_kitchen
                toggle: true

  - title: Salon
    icon: mdi:sofa
    cards:
      - title: Światło
        type: entities
        entities:
          - light.gateway_light_living_room
          - switch.light_coffee_table_living_room
      - title: Rozrywka
        type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.sony_kdl_50w809c
            name: Sony TV
            hide:
              source: true
      - title: Nawilżacz powietrza
        type: entities
        entities:
          - humidifier.evaporative_humidifier_office
          - switch.evaporative_humidifier_office_automations_enabled
          - input_select.evaporative_humidifier_office_mode
          - switch.evaporative_humidifier_office_led
          - switch.evaporative_humidifier_office_dry_mode
          - switch.evaporative_humidifier_office_child_lock
          - switch.evaporative_humidifier_office_buzzer
          - sensor.evaporative_humidifier_office_motor_speed
          - sensor.evaporative_humidifier_office_water_level
        show_header_toggle: false
        theme: default
      - title: Odkurzacz
        type: "custom:vacuum-card"
        entity: vacuum.vacuum_roborock_s50
        compact_view: false
        stats:
          default:
            - entity_id: sensor.vacuum_roborock_s50_main_brush_left
              value_template: '{{ (value | float(0) / 3600) | round(1) }}'
              unit: hours
              subtitle: Szczotka główna
            - entity_id: sensor.vacuum_roborock_s50_side_brush_left
              value_template: '{{ (value | float(0) / 3600) | round(1) }}'
              unit: hours
              subtitle: Szczotka boczna
            - entity_id: sensor.vacuum_roborock_s50_filter_left
              value_template: '{{ (value | float(0) / 3600) | round(1) }}'
              unit: hours
              subtitle: Filtr powietrza
            - entity_id: sensor.vacuum_roborock_s50_sensor_dirty_left
              value_template: '{{ (value | float(0) / 3600) | round(1) }}'
              unit: hours
              subtitle: Czujniki
          cleaning:
            - entity_id: sensor.vacuum_roborock_s50_current_clean_area
              unit: m2
              subtitle: Cleaning area
            - entity_id: sensor.vacuum_roborock_s50_current_clean_duration
              unit: minutes
              subtitle: Cleaning time
        shortcuts:
          - name: Clean entrance
            service: script.clean_entrance
            icon: 'mdi:door'
          - name: Clean hall
            service: script.clean_hall
            icon: "mdi:walk"
          - name: Clean kitchen
            service: script.clean_kitchen
            icon: "mdi:silverware-fork-knife"
          - name: Clean living room
            service: script.clean_living_room
            icon: "mdi:sofa"
          - name: Clean office
            service: script.clean_office
            icon: "mdi:laptop"
          - name: Clean bathroom
            service: script.clean_bathroom
            icon: "mdi:shower"
          - name: Clean bedroom
            service: script.clean_bedroom
            icon: "mdi:bed-empty"
          - name: Clean entire home
            service: script.clean_entire_home
            icon: "mdi:home"

  - title: Biuro
    icon: mdi:laptop
    cards:
      - title: Światło
        type: entities
        entities:
          - switch.light_1_office
          - switch.light_2_office
          - light.mi_led_desk_lamp

  - title: Korytarz
    icon: mdi:walk
    cards:
      - title: Światło
        type: entities
        entities:
          - light.gateway_light_hall
          - switch.light_1_hall
  
  - title: Sypialnia
    icon: mdi:bed-empty
    cards:
      - title: Światło
        type: entities
        entities:
          - light.yeelight_color_bedroom

      - type: vertical-stack
        cards:
          - title: Rozrywka
            type: entities
            entities:
              - name: Projektor 
                type: "custom:mini-media-player"
                entity: media_player.projector_bedroom
                hide:
                  source: true
                shortcuts:
                  columns: 3
                  buttons:
                    - type: script
                      name: "30 min"
                      id: script.projector_30_minutes_off
                    - type: script
                      name: "60 min"
                      id: script.projector_60_minutes_off
                    - type: script
                      name: "90 min"
                      id: script.projector_90_minutes_off
              - switch.projector_bedroom_off_timer
              - input_number.projector_bedroom_off_timer
              - sensor.projector_bedroom_off_timer_remaining

      - title: Oczyszczacz powietrza
        type: entities
        entities:
          - fan.air_purifier_bedroom
          - switch.air_purifier_bedroom_automations_enabled
          - input_select.air_purifier_bedroom_mode
          - number.air_purifier_bedroom_favorite_level
          - number.air_purifier_bedroom_fan_level
          - switch.air_purifier_bedroom_child_lock
          - switch.air_purifier_bedroom_led
          - switch.air_purifier_bedroom_buzzer
          - sensor.air_purifier_bedroom_motor_speed
          - sensor.air_purifier_bedroom_filter_life_remaining
        show_header_toggle: false
        theme: default