---
# All leaves home

# We're leaving home
- alias: All leaves home
  trigger:
    platform: state
    entity_id: group.family
    to: 'off'
    for:
      minutes: 3
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.wojciech_devices
      data:
        title: "Nikogo nie ma w domu."
        message: "Wyłączam światło."