---
# Justyna arrives to work

- alias: Presence - Justyna arrives to work
  trigger:
    platform: state
    entity_id: person.justyna
    to: 'ryvu'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.wojciech_devices
      data:
        title: Justyś dotarła do pracy.
        message: "Ciężko pracuje, by kot miał godne życie :)"

- alias: Presence - Wojciech get ride Justyna to work
  trigger:
    platform: state
    entity_id: person.wojciech
    to: 'ryvu'
  condition:
    - condition: time
      after: '15:00:00'
      before: '19:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.justyna_devices
      data:
        title: Muszek już czeka
        message: "Czem prędzej wsiadaj do Audiczki! :)"