---
# Kitchen wall switches automations

- alias: Toggle kitchen desk light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_kitchen_desk
      click_type: single
  action:
    service: light.toggle
    entity_id: light.shelly_kitchen_desk

- alias: Toggle kitchen table light
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_kitchen_table
      click_type: single
  action:
    service: light.toggle
    entity_id: light.gateway_light_living_room


- alias: Toggle kitchen table light
  trigger:
    - entity_id: sensor.0x00158d000456c6f3_click
      platform: state
      to: single
  action:
    - data:
        entity_id: light.shelly_kitchen_desk
      service: light.toggle