---
# Xiaomi Evaporative Humidifier 

# Mode change
- alias: Mode change
  trigger:
    platform: state
    entity_id: input_select.evaporative_humidifier_office_mode
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.evaporative_humidifier_office
      speed: '{{ states.input_select.evaporative_humidifier_office_mode.state }}' 

# Mode changed
- alias: Mode changed
  trigger:
    platform: state
    entity_id: fan.evaporative_humidifier_office
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ (state_attr('fan.evaporative_humidifier_office', 'speed') | string) != (states('input_select.evaporative_humidifier_office_mode') | string) }}"
  action:
    service: input_select.select_option
    entity_id: input_select.evaporative_humidifier_office_mode
    data_template:
      option: '{{ states.fan.evaporative_humidifier_office.attributes.speed }}'

# LED Brightness change
- alias: LED Brightness change
  trigger:
    entity_id: input_number.evaporative_humidifier_office_led_brightness
    platform: state
  action:
    service: xiaomi_miio.fan_set_led_brightness
    data_template:
      entity_id: fan.evaporative_humidifier_office
      brightness: '{{ states.input_number.evaporative_humidifier_office_led_brightness.state | int }}'   

# LED Brightness level changed
- alias: LED Brightness changed
  trigger:
    platform: state
    entity_id: fan.evaporative_humidifier_office
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ (state_attr('fan.evaporative_humidifier_office', 'led_brightness') | int) != (states('input_number.evaporative_humidifier_office_led_brightness') | int) }}"
  action:
    service: input_number.set_value
    entity_id: input_number.evaporative_humidifier_office_led_brightness
    data_template:
      value: '{{ states.fan.evaporative_humidifier_office.attributes.led_brightness }}'

# Turn the Humidifier on when humidity is below 50%
- alias: Turn Humidifier on
  trigger:
    - platform: time_pattern
      minutes: '/10'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.evaporative_humidifier_office_automations_enabled
        state: 'on'
      - condition: state
        entity_id: fan.evaporative_humidifier_office
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.ht_humidity_living_room
        below: '50'
      - condition: numeric_state
        entity_id: sensor.evaporative_humidifier_office_depth
        above: '15'
  action:
    - service: fan.turn_on
      entity_id: fan.evaporative_humidifier_office
    - service: fan.set_speed
      entity_id: fan.evaporative_humidifier_office
      data:
        speed: Auto

# Turn the Humidifier off when humidity is above 60
- alias: Turn Humidifer off
  trigger:
    - platform: numeric_state
      entity_id: sensor.ht_humidity_living_room
      above: '57'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.evaporative_humidifier_office_automations_enabled
        state: 'on'
      - condition: state
        entity_id: fan.evaporative_humidifier_office
        state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.evaporative_humidifier_office
    - service: notify.wojciech_devices
      data: 
        title: Wylaczam nawilzacz!
        message: "Za wilgotno.."

# Turn the Humidifier off when depth of water is below 15
- alias: Turn Humidifier off when depth is below than defined
  trigger:
    - platform: time_pattern
      minutes: '/10'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.evaporative_humidifier_office_automations_enabled
        state: 'on'
      - condition: state
        entity_id: fan.evaporative_humidifier_office
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.evaporative_humidifier_office_depth
        below: '35'
  action:
    - service: fan.turn_off
      entity_id: fan.evaporative_humidifier_office

