---
# Xiaomi Air Purifier 3

# Mode change
- alias: Mode change
  trigger:
    platform: state
    entity_id: input_select.air_purifier_bedroom_mode
  action:
    service: fan.set_preset_mode
    data_template:
      entity_id: fan.air_purifier_bedroom
      preset_mode: '{{ states.input_select.air_purifier_bedroom_mode.state }}' 

# Mode changed
- alias: Mode changed
  trigger:
    platform: state
    entity_id: fan.air_purifier_bedroom
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ (state_attr('fan.air_purifier_bedroom', 'preset_mode') | string) != (states('input_select.air_purifier_bedroom_mode') | string) }}"
  action:
    service: input_select.select_option
    entity_id: input_select.air_purifier_bedroom_mode
    data_template:
      option: '{{ states.fan.air_purifier_bedroom.attributes.preset_mode }}'

# Toggle automations depends on windows state
- alias: Toggle automations depends on window open/close state
  trigger:
    platform: state
    entity_id: group.all_windows
  action:
    - service_template: >
        {% if is_state('group.all_windows', 'on') %} switch.turn_off
        {% else %} switch.turn_on
        {% endif %}
      entity_id: switch.air_purifier_bedroom_automations_enabled
    - service_template: >
        {% if is_state('group.all_windows', 'on') and is_state('fan.air_purifier_bedroom', 'on') %} fan.turn_off
        {% else %} fan.turn_on
        {% endif %}
      entity_id: fan.air_purifier_bedroom