---
# Xiaomi Evaporative Humidifier 

# Mode change
- alias: Mode change
  trigger:
    platform: state
    entity_id: input_select.evaporative_humidifier_office_mode
  action:
    service: humidifier.set_mode
    data_template:
      mode: '{{ states.input_select.evaporative_humidifier_office_mode.state }}' 
      entity_id: humidifier.evaporative_humidifier_office

# Mode changed
- alias: Mode changed
  trigger:
    platform: state
    entity_id: humidifier.evaporative_humidifier_office
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ (state_attr('humidifier.evaporative_humidifier_office', 'mode') | string) != (states('input_select.evaporative_humidifier_office_mode') | string) }}"
  action:
    service: input_select.select_option
    entity_id: input_select.evaporative_humidifier_office_mode
    data_template:
      option: '{{ states.humidifier.evaporative_humidifier_office.attributes.mode }}'

# Turn the Humidifier on when humidity is below 50%
- alias: Turn Humidifier on
  trigger:
    - platform: time_pattern
      minutes: '/10'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.evaporative_humidifier_office_automations_enabled
        state: 'on'
      - condition: state
        entity_id: humidifier.evaporative_humidifier_office
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.ht_humidity_average_entire_home
        below: 50
      - condition: numeric_state
        entity_id: sensor.evaporative_humidifier_office_water_level
        above: 15
  action:
    - service: humidifier.turn_on
      entity_id: humidifier.evaporative_humidifier_office
    - service: humidifier.set_mode
      entity_id: humidifier.evaporative_humidifier_office
      data:
        mode: Auto

# Turn the Humidifier off when humidity is above 60
- alias: Turn Humidifer off
  trigger:
    - platform: numeric_state
      entity_id: sensor.ht_humidity_average_entire_home
      above: 57
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.evaporative_humidifier_office_automations_enabled
        state: 'on'
      - condition: state
        entity_id: humidifier.evaporative_humidifier_office
        state: 'on'
  action:
    - service: humidifier.turn_off
      entity_id: humidifier.evaporative_humidifier_office
    - service: notify.wojciech_devices
      data: 
        title: Wylaczam nawilzacz!
        message: "Za wilgotno.."
  mode: single

# Turn the Humidifier off when depth of water is below 15
- alias: Turn Humidifier off when depth is below than defined
  trigger:
    - platform: time_pattern
      minutes: '/10'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.evaporative_humidifier_office_automations_enabled
        state: 'on'
      - condition: state
        entity_id: humidifier.evaporative_humidifier_office
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.evaporative_humidifier_office_water_level
        below: '35'
  action:
    - service: humidifier.turn_off
      entity_id: humidifier.evaporative_humidifier_office

