---
# Determine Justyna home presence automations

- alias: Mark Justyna Home
  trigger:
    - platform: state
      entity_id: person.justyna
      to: 'home'
    - platform: state
      entity_id: input_boolean.justyna_wifi
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.justyna_home
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.justyna_home

- alias: Mark Justyna Away
  trigger:
    - platform: state
      entity_id: person.justyna
      to: 'not_home'
      for:
        minutes: 2
    - platform: state
      entity_id: input_boolean.justyna_wifi
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.justyna_home
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.justyna_home