---
# Determine Justyna home wifi connection automations

# Init "justyna_wifi" state
- alias: Init Justyna Wifi
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:30:00'
    - service_template: >
        {% if is_state('binary_sensor.oneplus_7t_ping', 'on') %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.justyna_wifi

# Turn "justyna_wifi" on
- alias: Mark Justyna Wifi connected
  trigger:
    - platform: state
      entity_id: binary_sensor.oneplus_7t_ping
      to: 'on'
  #   - platform: state
  #     entity_id: sensor.oneplus_7t_polaczenie_wi_fi
  #     to: 'Niasio.net'
  #   - platform: state
  #     entity_id: sensor.oneplus_7t_polaczenie_wi_fi
  #     to: 'Niasio5G.net'
  # condition: 
  #   - condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: binary_sensor.oneplus_7t_ping
  #         state: 'on'
  #       - condition: or
  #         conditions:
  #         - condition: state
  #           entity_id: input_boolean.justyna_wifi
  #           state: 'off'
  #         - condition: state
  #           entity_id: input_boolean.justyna_home
  #           state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.justyna_wifi, input_boolean.justyna_home

# Turn "justyna_wifi" off
- alias: Mark Justyna Wifi disconnected
  trigger:
    - platform: state
      entity_id: binary_sensor.oneplus_7t_ping
      to: 'off'
  #   - platform: state
  #     entity_id: sensor.oneplus_7t_polaczenie_wi_fi
  #     to: '<not connected>'
  # condition:
  #   - condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: binary_sensor.oneplus_7t_ping
  #         state: 'off'
  #       - condition: state
  #         entity_id: input_boolean.justyna_wifi
  #         state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.justyna_wifi