---
# Determine Justyna home presence automations

# Init "justyna_home" state
- alias: Init Justyna Home
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:01:00'
    - service_template: >
        {% if is_state('person.justyna', 'home') %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.justyna_home

# Turn "justyna_home" on
- alias: Mark Justyna Home
  trigger:
    - platform: state
      entity_id: person.justyna
      to: 'home'
    - platform: state
      entity_id: input_boolean.justyna_wifi
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.justyna_home
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.justyna_home

# Turn "justyna_home" off
- alias: Mark Justyna Away
  trigger:
    - platform: state
      entity_id: person.justyna
      to: 'not_home'
      for:
        minutes: 2
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.justyna_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.justyna_wifi
          state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.justyna_home