---
# Determine Wojciech home presence automations

# Init "wojciech_wifi" state
- alias: Init Wojciech Wifi
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:30:00'
    - service_template: >
        {% if is_state('binary_sensor.oneplus_7_ping', 'on') %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.wojciech_wifi

# Turn "wojciech_wifi, wojciech_home" on
- alias: Mark Wojciech Wifi connected
  trigger:
    - platform: state
      entity_id: binary_sensor.oneplus_7_ping
      to: 'on'
  #   - platform: state
  #     entity_id: sensor.oneplus_7_polaczenie_wi_fi
  #     to: 'Niasio.net'
  #   - platform: state
  #     entity_id: sensor.oneplus_7_polaczenie_wi_fi
  #     to: 'Niasio5G.net'
  # condition:
  #   - condition: and
  #     conditions:
  #     - condition: state
  #       entity_id: binary_sensor.oneplus_7_ping
  #       state: 'on'
  #     - condition: or
  #       conditions:
  #       - condition: state
  #         entity_id: input_boolean.wojciech_wifi
  #         state: 'off'
  #       - condition: state
  #         entity_id: input_boolean.wojciech_home
  #         state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wojciech_wifi, input_boolean.wojciech_home

# Turn "wojciech_wifi" off
- alias: Mark Wojciech Wifi disconnected
  trigger:
    - platform: state
      entity_id: binary_sensor.oneplus_7_ping
      to: 'off'
  #   - platform: state
  #     entity_id: sensor.oneplus_7_polaczenie_wi_fi
  #     to: '<not connected>'
  # condition:
  #   - condition: and
  #     conditions:
  #     - condition: state
  #       entity_id: binary_sensor.oneplus_7_ping
  #       state: 'off'
  #     - condition: state
  #       entity_id: input_boolean.wojciech_wifi
  #       state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wojciech_wifi

- alias: Mark Device Tracker Person Wojciech Wifi
  trigger:
    - platform: state
      entity_id: binary_sensor.wojciech_wifi
  action:
    - service: device_tracker.see
      data:
        dev_id: person_wojciech_wifi
        location_name: >
          {% if is_state('binary_sensor.wojciech_wifi', 'on') %} home
          {% else %} not_home
          {% endif %}