---
# Determine Wojciech home presence automations

# Init "wojciech_home" state
- alias: Init Wojciech Home
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:01:00'
    - service_template: >
        {% if is_state('person.wojciech', 'home') %} input_boolean.turn_on
        {% else %} input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.wojciech_home

# Turn "wojciech_home" on
- alias: Mark Wojciech Home
  trigger:
    - platform: state
      entity_id: person.wojciech
      to: 'home'
    - platform: state
      entity_id: input_boolean.wojciech_wifi
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.wojciech_home
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wojciech_home

# Turn "wojciech_home" off
- alias: Mark Wojciech Away
  trigger:
    - platform: state
      entity_id: person.wojciech
      to: 'not_home'
      for:
        minutes: 2
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.wojciech_home
          state: 'on'
        - condition: state
          entity_id: input_boolean.wojciech_wifi
          state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wojciech_home