- platform: template
  switches:
    door_entrance_contact:
      value_template: "{{ is_state('binary_sensor.door_entrance_contact','on') }}"
      turn_on:
        service: python_script.set_state
        data:
          entity_id: binary_sensor.door_entrance_contact
          state: 'on'
      turn_off:
        service: python_script.set_state
        data:
          entity_id: binary_sensor.door_entrance_contact
          state: 'off'
