- platform: template
  switches:
    projector_bedroom_off_timer:
      friendly_name: Timer wyłączania
      icon_template: "mdi:timer-outline"
      value_template: >
        {{ is_state('input_boolean.projector_bedroom_off_timer', 'on') }}
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.projector_bedroom_off_timer
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.projector_bedroom_off_timer