---
# Xiaomi Air Purifier 3

- platform: template
  switches:
    air_purifier_bedroom_led:
      friendly_name: "LED"
      value_template: "{{ is_state_attr('fan.air_purifier_bedroom', 'led', true) }}"
      turn_on:
        - service: xiaomi_miio.fan_set_led_on
          data:
            entity_id: fan.air_purifier_bedroom
      turn_off:
        - service: xiaomi_miio.fan_set_led_off
          data:
            entity_id: fan.air_purifier_bedroom
      icon_template: "mdi:lightbulb-outline"
    air_purifier_bedroom_child_lock:
      friendly_name: "Child lock"
      value_template: "{{ is_state_attr('fan.air_purifier_bedroom', 'child_lock', true) }}"
      turn_on:
        - service: xiaomi_miio.fan_set_child_lock_on
          data:
            entity_id: fan.air_purifier_bedroom
      turn_off:
        - service: xiaomi_miio.fan_set_child_lock_off
          data:
            entity_id: fan.air_purifier_bedroom
      icon_template: "mdi:lock-outline"
    air_purifier_bedroom_buzzer:
      friendly_name: "Buzzer"
      value_template: "{{ is_state_attr('fan.air_purifier_bedroom', 'buzzer', true) }}"
      turn_on:
        - service: xiaomi_miio.fan_set_buzzer_on
          data:
            entity_id: fan.air_purifier_bedroom
      turn_off:
        - service: xiaomi_miio.fan_set_buzzer_off
          data:
            entity_id: fan.air_purifier_bedroom
      icon_template: "mdi:volume-high"
    air_purifier_bedroom_manual_mode:
      friendly_name: "Manual mode"
      value_template: "{{ states.input_boolean.air_purifier_bedroom_manual_mode.state }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.air_purifier_bedroom_manual_mode
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.air_purifier_bedroom_manual_mode
      icon_template: mdi:hand-right