---
# Xiaomi Air Purifier 3

- platform: template
  switches:
    air_purifier_bedroom_led:
      friendly_name: "LED"
      value_template: "{{ is_state('select.air_purifier_bedroom_led_brightness', 'dim') }}"
      turn_on:
        - service: select.select_option
          data:
            entity_id: select.air_purifier_bedroom_led_brightness
            option: 'dim'
      turn_off:
        - service: select.select_option
          data:
            entity_id: select.air_purifier_bedroom_led_brightness
            option: 'off'
      icon_template: "mdi:lightbulb-outline"
     
    air_purifier_bedroom_automations_enabled:
      friendly_name: "Automations enabled"
      value_template: "{{ states.input_boolean.air_purifier_bedroom_automations_enabled.state }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.air_purifier_bedroom_automations_enabled
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.air_purifier_bedroom_automations_enabled
      icon_template: mdi:autorenew