---
# Xiaomi Evaporative Humidifier 

- platform: template
  switches:
    evaporative_humidifier_office_led:
      friendly_name: "LED"
      value_template: "{{ is_state('select.evaporative_humidifier_office_led_brightness', 'dim') }}"
      turn_on:
        - service: select.select_option
          data:
            entity_id: select.evaporative_humidifier_office_led_brightness
            option: 'dim'
      turn_off:
        - service: select.select_option
          data:
            entity_id: select.evaporative_humidifier_office_led_brightness
            option: 'off'
      icon_template: "mdi:lightbulb-outline"

    evaporative_humidifier_office_automations_enabled:
      friendly_name: "Automations enabled"
      value_template: "{{ states.input_boolean.evaporative_humidifier_office_automations_enabled.state }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.evaporative_humidifier_office_automations_enabled
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.evaporative_humidifier_office_automations_enabled
      icon_template: mdi:autorenew