---
# Cat toilet

- platform: template
  sensors:
    cat_toilet_activity:
      device_class: motion
      value_template: >-
        {{ is_state('binary_sensor.motion_sensor_cat_toilet', 'on') and
           is_state('binary_sensor.door_cat_toilet_contact', 'off') }}
