---
# Justyna Home Wifi states

- platform: template
  sensors:
    justyna_wifi:
        device_class: connectivity
        value_template: >-
          {{ is_state('device_tracker.iphone_justyna_arp', 'home') }}

      