---
# Ping OnePlus 7

- platform: command_line
  name: OnePlus 7 ping
  command: 'ping -W 1 -c 3 192.168.55.5 > /dev/null 2>&1 && echo success || echo fail'
  device_class: connectivity
  payload_on: "success"
  payload_off: "fail"
  scan_interval: 30
