- platform: bayesian
  prior: 0.6
  name: Wojciech Presence
  device_class: 'presence'
  probability_threshold: 0.9
  observations:
    - entity_id: device_tracker.oneplus_7
      prob_given_true: 0.7
      prob_given_false: 0.3
      platform: state
      to_state: 'home'

    - entity_id: sensor.oneplus_7_polaczenie_wi_fi
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: state
      to_state: 'Niasio5G.net'

    - entity_id: device_tracker.oneplus_7_ping
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: state
      to_state: 'home'