---
# Wojciech Home Wifi states

- platform: template
  sensors:
    wojciech_wifi:
        device_class: connectivity
        value_template: >-
          {{ is_state('input_boolean.wojciech_wifi', 'on') }}
      