---
# Wojciech Home Wifi states

- platform: template
  sensors:
    wojciech_wifi:
        device_class: connectivity
        value_template: >-
          {{ is_state('device_tracker.iphone_wojciech_arp', 'home') }}
      