---
# Kitchen lights automations

- alias: Turn off kitchen lights after 3 minutes when Justyna not home
  trigger:
    - platform: state
      entity_id: switch.light_desk_kitchen
      to: 'on'
      for: '00:03:00'
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: person.justyna
          state: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.light_desk_kitchen

