---
# Presence 

# Justyna leaves home
- alias: Presence - Justyna leaves home
  trigger:
    platform: state
    entity_id: person.justyna
    from: 'home'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action: 
    - service: notify.wojciech_devices
      data:
        title: Justyś wychodzi z domu.
        message: "Pewnie idzie do pracy.."

# Justyna arrives to work
- alias: Presence - Justyna arrives to work
  trigger:
    platform: state
    entity_id: person.justyna
    to: 'ryvu'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.wojciech_devices
      data:
        title: Justyś dotarła do pracy.
        message: "Ciężko pracuje, by kot miał godne życie :)"
        
# Justyna leaves work
- alias: Presence - Justyna leaves work
  trigger:
    platform: state
    entity_id: person.justyna
    from: 'ryvu'
  condition:
    - condition: time
      after: '15:00:00'
      before: '18:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.wojciech_devices
      data:
        title: Justyna wychodzi z pracy.
        message: "Będzie za niedługo."

# Justyna arrives to home
- alias: Presence - Justyna arrives to home
  trigger:
    platform: state
    entity_id: person.justyna
    to: 'home'
  condition:
    - condition: time
      after: '15:00:00'
      before: '18:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action: 
    - service: notify.wojciech_devices
      data:
        title: Justyna wróciła do domu.
        message: "Właśnie weszła :)!"