# ---
# Tuya devices

- platform: switch
  name: Light 1 Entrance
  entity_id: switch.light_1_entrance

- platform: switch
  name: Light 1 Kitchen Entrance
  entity_id: switch.light_1_kitchen_entrance

- platform: switch
  name: Light 1 Kitchen
  entity_id: switch.light_1_kitchen

- platform: switch
  name: Light 2 Kitchen
  entity_id: switch.light_2_kitchen

- platform: switch
  name: Light 1 Hall
  entity_id: switch.light_1_hall

- platform: switch
  name: Coffee Table Light Living Room
  entity_id: switch.coffee_table_light_living_room